create extension if not exists pgcrypto;

create table public.bot_settings (
  chat_id text primary key,
  selected_symbols jsonb not null default '[]'::jsonb,
  capital_by_symbol jsonb not null default '{}'::jsonb,
  execution_mode text not null default 'paper' check (execution_mode in ('paper','testnet','live')),
  max_concurrent_positions integer not null default 3 check (max_concurrent_positions > 0),
  risk_per_trade_pct numeric not null default 0.005 check (risk_per_trade_pct > 0 and risk_per_trade_pct <= 0.02),
  daily_loss_limit_pct numeric not null default 0.02 check (daily_loss_limit_pct > 0 and daily_loss_limit_pct <= 0.20),
  updated_at timestamptz not null default now()
);

create table public.market_candles (
  symbol text not null,
  timeframe text not null,
  open_time bigint not null,
  close_time bigint not null,
  open_price numeric not null,
  high_price numeric not null,
  low_price numeric not null,
  close_price numeric not null,
  volume numeric not null,
  is_closed boolean not null default true,
  source text not null default 'binance',
  created_at timestamptz not null default now(),
  primary key (symbol, timeframe, open_time)
);

create table public.fvg_zones (
  id uuid primary key default gen_random_uuid(),
  symbol text not null,
  timeframe text not null,
  fvg_direction text not null check (fvg_direction in ('BULLISH','BEARISH')),
  candle_1_open_time bigint not null,
  candle_2_open_time bigint not null,
  candle_3_open_time bigint not null,
  zone_low numeric not null,
  zone_high numeric not null,
  status text not null default 'ACTIVE' check (status in ('ACTIVE','MITIGATED','INVERTED','EXPIRED')),
  created_at timestamptz not null default now(),
  inverted_at timestamptz null,
  unique (symbol, timeframe, candle_1_open_time, candle_3_open_time)
);

create table public.ifvg_zones (
  id uuid primary key default gen_random_uuid(),
  fvg_id uuid not null references public.fvg_zones(id) on delete cascade,
  symbol text not null,
  timeframe text not null,
  direction text not null check (direction in ('BULLISH','BEARISH')),
  inverted_at bigint not null,
  retest_at bigint null,
  zone_low numeric not null,
  zone_high numeric not null,
  status text not null default 'ACTIVE' check (status in ('ACTIVE','RETESTED','FAILED','EXPIRED')),
  created_at timestamptz not null default now(),
  unique (fvg_id, inverted_at)
);

create table public.signals (
  id uuid primary key default gen_random_uuid(),
  user_id text not null,
  ifvg_id uuid null references public.ifvg_zones(id),
  symbol text not null,
  timeframe text not null,
  side text not null check (side in ('BUY','SELL')),
  generated_at timestamptz not null default now(),
  candle_open_time bigint not null,
  entry_price numeric not null,
  stop_loss numeric not null,
  take_profit numeric not null,
  reason text not null,
  risk_reward numeric not null,
  strategy_version text not null default 'ifvg_v1',
  metadata jsonb not null default '{}'::jsonb,
  status text not null default 'NEW' check (status in ('NEW','ACCEPTED','REJECTED','EXPIRED','EXECUTED')),
  created_at timestamptz not null default now(),
  unique (user_id, symbol, timeframe, candle_open_time, strategy_version)
);

create table public.signal_features (
  id bigint generated by default as identity primary key,
  signal_id uuid not null references public.signals(id) on delete cascade,
  feature_name text not null,
  feature_value numeric null,
  passed boolean null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (signal_id, feature_name)
);

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id text not null,
  signal_id uuid null references public.signals(id),
  position_id uuid null,
  client_order_id text not null unique,
  exchange_order_id text null,
  mode text not null check (mode in ('paper','testnet','live')),
  symbol text not null,
  side text not null check (side in ('BUY','SELL')),
  order_type text not null,
  status text not null default 'INTENT' check (status in ('INTENT','NEW','PARTIALLY_FILLED','FILLED','CANCELED','REJECTED','UNKNOWN')),
  requested_qty numeric not null,
  filled_qty numeric not null default 0,
  avg_fill_price numeric null,
  limit_price numeric null,
  stop_price numeric null,
  sent_at timestamptz null,
  last_checked_at timestamptz null,
  raw_response jsonb not null default '{}'::jsonb,
  error_message text null,
  created_at timestamptz not null default now()
);

create table public.positions (
  id uuid primary key default gen_random_uuid(),
  user_id text not null,
  signal_id uuid null references public.signals(id),
  entry_order_id uuid null references public.orders(id),
  symbol text not null,
  side text not null check (side in ('BUY','SELL')),
  mode text not null check (mode in ('paper','testnet','live')),
  quantity numeric not null,
  capital_allocated numeric not null,
  entry_price numeric not null,
  stop_loss numeric not null,
  take_profit numeric not null,
  status text not null default 'OPEN' check (status in ('OPEN','CLOSING','CLOSED','RECONCILIATION_REQUIRED')),
  exit_price numeric null,
  realized_pnl numeric null,
  fees_paid numeric not null default 0,
  opened_at timestamptz not null default now(),
  closed_at timestamptz null,
  close_reason text null,
  created_at timestamptz not null default now()
);

create table public.risk_events (
  id bigint generated by default as identity primary key,
  user_id text not null,
  symbol text null,
  event_type text not null,
  severity text not null default 'WARNING' check (severity in ('INFO','WARNING','CRITICAL')),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.system_events (
  id bigint generated by default as identity primary key,
  user_id text not null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.runtime_state (
  user_id text primary key,
  execution_mode text not null default 'paper',
  live_gate_open boolean not null default false,
  live_gate_reason text not null default 'paper_mode',
  runtime_started boolean not null default false,
  market_data_fresh boolean not null default false,
  websocket_connected boolean not null default false,
  user_data_stream_connected boolean not null default false,
  reconciled boolean not null default false,
  startup_stage text not null default 'idle',
  selected_symbols jsonb not null default '[]'::jsonb,
  market_status jsonb not null default '{}'::jsonb,
  metrics jsonb not null default '{}'::jsonb,
  cycle_count bigint not null default 0,
  signal_count bigint not null default 0,
  rejected_signal_count bigint not null default 0,
  updated_at timestamptz not null default now()
);

create index market_candles_symbol_tf_time_idx on public.market_candles(symbol, timeframe, open_time desc);
create index fvg_zones_symbol_tf_status_idx on public.fvg_zones(symbol, timeframe, status, created_at desc);
create index ifvg_zones_symbol_tf_status_idx on public.ifvg_zones(symbol, timeframe, status, created_at desc);
create index signals_user_symbol_time_idx on public.signals(user_id, symbol, generated_at desc);
create index orders_user_status_idx on public.orders(user_id, status, created_at desc);
create index positions_user_status_idx on public.positions(user_id, status, opened_at desc);
create index risk_events_created_idx on public.risk_events(created_at desc);
create index system_events_created_idx on public.system_events(created_at desc);

alter table public.bot_settings enable row level security;
alter table public.market_candles enable row level security;
alter table public.fvg_zones enable row level security;
alter table public.ifvg_zones enable row level security;
alter table public.signals enable row level security;
alter table public.signal_features enable row level security;
alter table public.orders enable row level security;
alter table public.positions enable row level security;
alter table public.risk_events enable row level security;
alter table public.system_events enable row level security;
alter table public.runtime_state enable row level security;

grant usage on schema public to service_role;
grant select, insert, update, delete on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;
notify pgrst, 'reload schema';
