-- Destructive reset of the application's public schema.
-- This intentionally removes all existing public tables, functions, and data.
-- Supabase auth/storage schemas are not touched.

drop schema if exists public cascade;
create schema public;
grant usage on schema public to anon, authenticated, service_role;
grant all on schema public to postgres, service_role;

create extension if not exists pgcrypto;

create table public.bot_settings (
  chat_id text primary key,
  selected_symbols jsonb not null default '[]'::jsonb,
  capital_by_symbol jsonb not null default '{}'::jsonb,
  max_concurrent_positions integer not null default 5,
  daily_loss_limit_pct numeric not null default 0.09,
  updated_at timestamptz not null default now()
);

create table public.signals (
  id uuid primary key default gen_random_uuid(),
  user_id text not null,
  symbol text not null,
  timeframe text not null,
  generated_at timestamptz not null,
  candle_open_time bigint not null,
  entry_price numeric not null,
  stop_loss numeric not null,
  take_profit numeric not null,
  reason text not null,
  risk_reward numeric not null,
  status text not null default 'NEW',
  created_at timestamptz not null default now()
);

create table public.virtual_positions (
  id uuid primary key,
  user_id text not null,
  signal_id uuid null references public.signals(id),
  symbol text not null,
  capital_allocated numeric not null,
  entry_price numeric not null,
  stop_loss numeric not null,
  take_profit numeric not null,
  quantity numeric not null,
  opened_at timestamptz not null,
  status text not null default 'OPEN',
  exit_price numeric null,
  closed_at timestamptz null,
  realized_pnl numeric null,
  close_reason text null,
  created_at timestamptz not null default now()
);

create table public.trade_events (
  id bigint generated by default as identity primary key,
  user_id text not null,
  position_id uuid not null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.system_events (
  id bigint generated by default as identity primary key,
  user_id text not null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index signals_user_symbol_time_idx on public.signals(user_id, symbol, generated_at desc);
create index positions_user_status_idx on public.virtual_positions(user_id, status);
create index system_events_created_idx on public.system_events(created_at desc);

alter table public.bot_settings enable row level security;
alter table public.signals enable row level security;
alter table public.virtual_positions enable row level security;
alter table public.trade_events enable row level security;
alter table public.system_events enable row level security;

grant select, insert, update, delete on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;

notify pgrst, 'reload schema';
