create extension if not exists pgcrypto;

create table if not exists public.bot_settings (
  chat_id text primary key,
  selected_symbols jsonb not null default '[]'::jsonb,
  capital_by_symbol jsonb not null default '{}'::jsonb,
  max_concurrent_positions integer not null default 5,
  daily_loss_limit_pct numeric not null default 0.09,
  updated_at timestamptz not null default now()
);

create table if not exists public.signals (
  id uuid primary key default gen_random_uuid(),
  user_id text not null,
  symbol text not null,
  timeframe text not null,
  generated_at timestamptz not null,
  candle_open_time bigint not null,
  entry_price numeric not null,
  stop_loss numeric not null,
  take_profit numeric not null,
  reason text not null,
  risk_reward numeric not null,
  status text not null default 'NEW',
  created_at timestamptz not null default now()
);

create table if not exists public.virtual_positions (
  id uuid primary key,
  user_id text not null,
  signal_id uuid null references public.signals(id),
  symbol text not null,
  capital_allocated numeric not null,
  entry_price numeric not null,
  stop_loss numeric not null,
  take_profit numeric not null,
  quantity numeric not null,
  opened_at timestamptz not null,
  status text not null default 'OPEN',
  exit_price numeric null,
  closed_at timestamptz null,
  realized_pnl numeric null,
  close_reason text null,
  created_at timestamptz not null default now()
);

create table if not exists public.trade_events (
  id bigint generated by default as identity primary key,
  user_id text not null,
  position_id uuid not null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.system_events (
  id bigint generated by default as identity primary key,
  user_id text not null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.runtime_state (
  user_id text primary key,
  runtime_started boolean not null default false,
  websocket_connected boolean not null default false,
  startup_stage text not null default 'idle',
  websocket_last_message_at timestamptz null,
  websocket_connected_at timestamptz null,
  websocket_last_error text null,
  websocket_last_close_code text null,
  websocket_last_close_reason text null,
  websocket_active_stream_url text null,
  selected_symbols jsonb not null default '[]'::jsonb,
  capital_by_symbol jsonb not null default '{}'::jsonb,
  strategy_ready_symbols jsonb not null default '[]'::jsonb,
  live_data_available boolean not null default false,
  live_data_source text not null default 'none',
  market_status jsonb not null default '{}'::jsonb,
  metrics jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create index if not exists signals_user_symbol_time_idx on public.signals(user_id, symbol, generated_at desc);
create index if not exists positions_user_status_idx on public.virtual_positions(user_id, status);
create index if not exists system_events_created_idx on public.system_events(created_at desc);
create index if not exists runtime_state_updated_idx on public.runtime_state(updated_at desc);

alter table public.bot_settings enable row level security;
alter table public.signals enable row level security;
alter table public.virtual_positions enable row level security;
alter table public.trade_events enable row level security;
alter table public.system_events enable row level security;
alter table public.runtime_state enable row level security;

grant usage on schema public to service_role;
grant select, insert, update, delete on table public.runtime_state to service_role;

-- The server uses SUPABASE_KEY only on Render. Use the Supabase service-role key
-- server-side if RLS is enabled; never expose it to Telegram or a browser.
