# config/settings.py
import sys
from . import (
    DEBUG_MODE, TELEGRAM_TOKEN, ADMIN_ID, RAW_DATABASE_URL, DATABASE_URL,
    REDIS_HOST, REDIS_PORT, REDIS_PASSWORD, PORT, WEBHOOK_URL,
    BINANCE_API_KEY, BINANCE_API_SECRET, BINANCE_WS_URL,
    DEFAULT_CAPITAL, TRADE_FEE, HTF_MODE, SUPABASE_URL, SUPABASE_KEY,
    LOG_LEVEL, validate_config as vc
)

# Derived settings
REDIS_URL = f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}"
SIGNAL_MODE = True
LIVE_MODE = False
SIMULATION_MODE = False
SYMBOL = "XAUUSD"
CAPITAL = DEFAULT_CAPITAL
RISK_PER_TRADE = 1.0
TIMEFRAME = "M15"

def validate_config():
    return vc()
